#!/bin/bash
if [ -z "$1" ]; then
    COMMIT=HEAD
else
    COMMIT=$1
fi
# git show $COMMIT --summary
HASH=$(git log --pretty=format:'%h' -n 1 $1)
echo -n $HASH | xclip -selection clipboard

# COLOR CODE
# https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux
# Black        0;30     Dark Gray     1;30
# Red          0;31     Light Red     1;31
# Green        0;32     Light Green   1;32
# Brown/Orange 0;33     Yellow        1;33
# Blue         0;34     Light Blue    1;34
# Purple       0;35     Light Purple  1;35
# Cyan         0;36     Light Cyan    1;36
# Light Gray   0;37     White         1;37
#    .---------- constant part!
#    vvvv vvvv-- the code from above
ORANGE='\033[0;33m'
NC='\033[0m' # No Color

echo -e "Copyed $ORANGE$HASH$NC to clipboard"
